### ISSUE TITLE
All command doesnt seem to be working

### ISSUE THREAD

**Issue by SuixideBunneh** [TheViperShow/SystemInfo#3]
I have OP, I also have systeminfo permission, everytime I typed a command, it says Unknown command. Type /help for help. Also, in the plugin.yml, commands were not stated. I am using 1.0.9 version.

**Comment by SuixideBunneh** [comment]
08.03 07:10:21 [Server] Server thread/INFO Enabling SystemInfo v1.0.9
08.03 07:10:21 [Server] Server thread/ERROR Error occurred while enabling SystemInfo v1.0.9 (Is it up to date?)
08.03 07:10:21 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Bukkit.getCommandMap()Lorg/bukkit/command/CommandMap;
08.03 07:10:21 [Server] INFO at me.thevipershow.systeminfo.SystemInfo.onEnable(SystemInfo.java:32) ~[?:?]
08.03 07:10:21 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
08.03 07:10:21 [Server] INFO at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
08.03 07:10:21 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
08.03 07:10:21 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [skyblock1.14.jar:git-Spigot-56f8471-3e3818b]
08.03 07:10:21 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by SuixideBunneh** [comment]
Minecraft server version 1.14.4.

**Comment by TheViperShow** [comment]
Are you using Spigot or Paper 1.14.4?
