### ISSUE TITLE
warn message

### ISSUE THREAD

**Issue by seema84** [TheViperShow/SystemInfo#5]
Version: v1.0.14
Paper: 1.15.2 (Build-372)

[Server thread/INFO]: [SystemInfo] Could not find PlaceholderAPI, placeholders won't be available.
[Server thread/WARN]: [oshi.util.GlobalConfig] No default configuration found

I am not sure but does this warning come from Systeminfo?

**Comment by TheViperShow** [comment]
Ignore it.
