### ISSUE TITLE
Placeholder not working.

### ISSUE THREAD

**Issue by RzR32** [TheViperShow/SystemInfo#9]
Hey, unfortunately I can't get your plugin to run with the PlaceholderAPI. The console always says that he cannot find it.

I also tried some other Version's from SystemInfo and PlaceholderAPI but it didn't work.

Did I miss something or is it a bug?

(Server Version: Paper 1.16.4)

![image](https://user-images.githubusercontent.com/46526880/104431798-9c3ba580-5588-11eb-9804-8514b300d480.png)

**Comment by TheViperShow** [comment]
What version is the placeholder API plugin

**Comment by RzR32** [comment]
in this case the latest version, PlaceholderAPI 2.10.9

**Comment by TheViperShow** [comment]
Issue should be fixed. Check JAR 1.3.5

**Comment by RzR32** [comment]
Hey, if i press download i alway get the wrong .jar i guess. 
("safechat-downloader-0.0.3-SNAPSHOT.jar" instead of "SystemInfo-1.3.5.jar" or so)

... is that normal or do i something wrong?

**Comment by TheViperShow** [comment]
Uhhhh i did a fail

**Comment by TheViperShow** [comment]
Did that got fixed right? :flushed:

**Comment by RzR32** [comment]
Now its fine working ^^
